#!/bin/bash
version=0.1
# Version Log

print_message () {
  echo '
###################################
Trimmomatic Batch Version '$version'

Created by Guilherme Azevedo 2021 
###################################

This program runs Trimmomatic in batch mode and prepares the output for phyluce

Usage:

trimmobatch -I InputFileList -R RawReads -O OutputPrefix [-h] [... OTHER_OPTIONAL_ARGUMENTS] 

      -I  InputFileList       The comma delimited file with the name of the files to be processed folowed by the desired output name for the final assembly file
      -R  RawReads            The folder with the raw reads to be processed
      -O  OutputPrefix        The name of the folder in whcih the final assemblies will be saved
      -a  adaptersfasta       Fastafile with the adapeter sequences 
      -m  minimum_length      Minimum length of the sequence to be kept. Default 40 (same as in phyluce)
      -n  nthreads            Number of cores. Default: 16
      -h  help

See Trimmomatic (http://www.usadellab.org/cms/?page=trimmomatic) web page for more information

All default parameters are the same as used in phyluce v1.7.1.

'
exit
}


#Set variables and default values
InputFileList=""
RawReads=""
OutputPrefix=""
adaptersfasta="all_paired.fa"
min_len=40
nthreads=16




while getopts "I:R:O:a:n:m:h" flag; do
    case "${flag}" in
            I)  InputFileList=${OPTARG};;
            R)  RawReads=${OPTARG};;
            O)  OutputPrefix=${OPTARG};;
            a)  adaptersfasta=${OPTARG};;
            n)  nthreads=${OPTARG};;
            m)  min_len=${OPTARG};;
            h)  print_message;;
            ?)  printf '\nUsage: %s -I INPUT_FOLDER -O OUTPUT_PREFIX -R RAW_READS -a PATH_TO_ADAPTERS_FASTA [-h] [... OTHER_OPTIONAL_ARGUMENTS] \n \nRun this program with flag -h for full usage options\n' $0; exit 2;;                                                                                                                                                                                          
    esac
done


if [ "$InputFileList" == "" ]
  then
     echo "Input file needs to be specified with the flag -I"
     echo
     echo -e '\nUsage: trimmobatch -I INPUT_FOLDER -O OUTPUT_PREFIX -R RAW_READS -a PATH_TO_ADAPTERS_FASTA [-h] [... OTHER_OPTIONAL_ARGUMENTS] \n \nRun this program with flag -h for full usage options\n'
     exit
  else
     echo "Input file "$InputFileList""
fi


if [ "$RawReads" == "" ]
  then
     echo "Path to folder with raw reads needs to be specified with the flag -R"
     echo
     echo -e '\nUsage: trimmobatch -I INPUT_FOLDER -O OUTPUT_PREFIX -R RAW_READS -a PATH_TO_ADAPTERS_FASTA [-h] [... OTHER_OPTIONAL_ARGUMENTS] \n \nRun this program with flag -h for full usage options\n'
     exit
  else
     echo "Raw reads folder "$RawReads""
fi

if [ "$OutputPrefix" == "" ]
  then
     echo "Path to folder with raw reads needs to be specified with the flag -R"
     echo
     echo -e '\nUsage: trimmobatch -I INPUT_FOLDER -O OUTPUT_PREFIX -R RAW_READS -a PATH_TO_ADAPTERS_FASTA [-h] [... OTHER_OPTIONAL_ARGUMENTS] \n \nRun this program with flag -h for full usage options\n'
     exit
  else
     echo "Output folder "$OutputPrefix""
fi



progressfile=$OutputPrefix".progress.txt"
touch $progressfile

outdir=$OutputPrefix"_clean_fastq"
mkdir $outdir

filelist=$(paste -d " " $InputFileList)
cd $RawReads
rawreadspath=$(pwd)
cd ..

for line in $filelist
  do
    r1=$(echo $line | cut -f1 -d",")
    r2=$(echo $line | cut -f2 -d",")
    out=$(echo $line | cut -f3 -d",")
    
    echo "processing "$out"" >> $progressfile
	trimmomatic PE -threads $nthreads $rawreadspath/$r1 $rawreadspath/$r2 $out"-READ1.fastq.gz" $out"-READ1-single.fastq.gz" $out"-READ2.fastq.gz" $out"-READ2-single.fastq.gz" ILLUMINACLIP:$adaptersfasta:2:30:10 LEADING:5 TRAILING:15 SLIDINGWINDOW:4:15 MINLEN:$min_len
	cat $out"-READ1-single.fastq.gz" $out"-READ2-single.fastq.gz" > $out"-READ-singleton.fastq.gz"
	rm $out"-READ1-single.fastq.gz" $out"-READ2-single.fastq.gz"
    mkdir $outdir/$out
	mkdir $outdir/$out/split-adapter-quality-trimmed
	cd $outdir/$out/split-adapter-quality-trimmed
	mv ../../../*READ*.fastq.gz .
    cd ../../..

 done


echo "Finished trimming" >> $progressfile

